#!/bin/bash
#
#write a script that:

#Go over all files in a directory and delete all files that has names shorter than first parameter.


filename=$(ls  "$1")
for i in ${filename}
  do 
	count=$(echo -n "$i"|wc -c)
	if [[ ${count} -lt 5 ]] && [[ -f $i ]] 
  then
 	printf  "$i <5 \n"
	 read -p "are you want to delete $i  y/n : " delete
		if [[ $delete = y ]]
		then
			rm  -f $i 
			  if [[ -f "i" ]]
			     then
				printf "$i not deleted"
				echo "delete a file run manually: rm $i"
			  else
				printf "$i deleted \n"
			fi
		else
			printf "$i not deleted \n"
	fi	
 fi
done
