#!/bin/bash
#
#
#Write a script that goes over all files in a directory, and finds all files that have the word PASSWORD in them.
#The script deletes those files, and create a report file that says what files were removed.



echo " I can search if password exist in  file in directory"
read -p "what to searche : " password
filename=$(ls "$1")
for i in ${filename} 
  do 
	if [ -f $1/$i ] &&  grep -q "${password}" $1/$i   
  then
 	printf  "$i  ${password}  exists \n"
	 read -p "Do delete y/n : " delete
		if [[ $delete = y ]]
		then
			rm $1/$i -f
			if [[ -f "$1/$i" ]]
			     then
				printf "$i not deleted \n"
			else
				printf "$i deleted \n"
			fi
		   else
			printf "$i not deleted \n"
		fi	
		
fi
done

