#!/bin/bash

#Final bash project:

#Write a "user management" script (file called userman that implements a command line interface, with the following commands:
#new - creates a new user
#del - deletes a user
#find - finds a user
#list - list all users
#exit - leaves the script.

#When a new user is created, the script creates a file like the following:

#adam.user
#with the content:
#name: adam
#password:  54276 

#(this is a random number you create automatically)




printf "hello  \n"
printf "for management user plese enter command and user name \n"
printf "for example : find moshe \n"
printf "can use command below : \n"
printf "new - creates a user \n"
printf "del - delete  a user \n"
printf "find- finds a user \n"
printf "list - list all users \n"
printf "exit - leave the script \n" 
read -p " users> " -a usrmgmt


while [[ ${usrmgmt[0]} != exit ]]
   do
          if [ ${usrmgmt[0]} == new ]
    		then
			touch ${usrmgmt[1]}.user
			printf "name:  ${usrmgmt[1]} \n" >  ${usrmgmt[1]}.user
			printf "password:  $RANDOM  \n" >> ${usrmgmt[1]}.user
			printf " Created user ${usrmgmt[1]} \n"


 	    elif [[ ${usrmgmt[0]} == del ]]
     		then
			rm ${usrmgmt[1]}.user
			printf " ${usrmgmt[1]}  deleted \n"


  	    elif [[ ${usrmgmt[0]} == find ]]
     		then
			if [  -f ${usrmgmt[1]}.user ]
			   then
	       			ls |grep ${usrmgmt[1]}.user
	       			cat ${usrmgmt[1]}.user
			else
	        		 printf " No user ${usrmgmt[1]} \n"
			fi


	    elif [[ ${usrmgmt[0]} == list ]]
			then
			usr=$(ls *.user 2> /dev/null)
				if [[ $? -gt 0 ]]
				  then
					printf "No Users  \n"	
        			  else
					ls |grep .user|cut -f1 -d '.'
				fi
	fi

	read -p " users> " -a usrmgmt

done
